apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: "0.13.11"
    chart: metallb
    helm:
      values: |
        existingConfigMap: metallb-config
        config:
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - 172.18.0.2-172.18.0.5
        rbac:
          create: true
        psp:
          create: true
        serviceAccounts:
          controller:
            create: true
            name: ""
          speaker:
             create: true
            name: ""
        controller:
          image:
            repository: metallb/controller
            tag: v0.8.1
            pullPolicy: IfNotPresent
          resources: {}
          nodeSelector: {}
          tolerations: []
          affinity: {}
        speaker:
          image:
            repository: metallb/speaker
            tag: v0.8.1
            pullPolicy: IfNotPresent
          resources: {}
          nodeSelector: {}
          tolerations: []
          affinity: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true